services:
  # SQLite profile
  app-sqlite:
    profiles:
    - sqlite
    build:
      context: .
      target: prod
    command: yarn start:dev
    environment:
      REPO_CONNECTION: /opt/epp-data/data.db
    ports:
    - "8080:3000"
    volumes:
    - ./src:/opt/epp/src
    - epp-data:/opt/epp-data

  # couchdb profile
  app-couchdb:
    profiles:
    - couchdb
    depends_on:
      create-database:
        condition: service_completed_successfully
    build:
      context: .
      target: prod
    command: yarn start:dev
    environment:
      REPO_TYPE: CouchDB
      REPO_CONNECTION: http://couchdb:5984/
      REPO_USERNAME: admin
      REPO_PASSWORD: testtest
    ports:
    - "8080:3000"
    volumes:
    - ./src:/opt/epp/src
    - epp-data:/opt/epp-data
  couchdb:
    profiles:
    - couchdb
    image: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: testtest
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:5984"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    ports:
    - "5984:5984"
    volumes:
    - couchdb:/home/couchdb/data
  create-database:
    profiles:
    - couchdb
    depends_on:
      couchdb:
        condition: service_healthy
    image: curlimages/curl
    entrypoint: sh
    command: -c 'sleep 5; curl -X PUT -u admin:testtest http://couchdb:5984/epp'
volumes:
  epp-data:
  couchdb:
