services:
  image-server:
    build:
      context: image-server
    ports:
    - "8182:8182"
    volumes:
    - ./image-server/dev-cantaloupe.properties:/opt/cantaloupe/cantaloupe.properties
    - ./data:/opt/epp/data

  sass-watch:
    build:
      context: .
      target: prod
    command: yarn sass:dev
    volumes:
    - ./src:/opt/epp/src
    - styles:/opt/epp/public/styles

  # mongodb profile
  app-mongodb:
    build:
      context: .
      target: prod
    command: yarn start:dev
    environment:
      REPO_TYPE: MongoDB
      REPO_CONNECTION: mongodb:27017
      REPO_USERNAME: admin
      REPO_PASSWORD: testtest
      IIIF_SERVER: http://localhost:8182
    ports:
      - "8080:3000"
    volumes:
      - ./src:/opt/epp/src
      - styles:/opt/epp/public/styles
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: testtest
    volumes:
      - data:/home/couchdb/data

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=dracula
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=testtest
    depends_on:
      - mongodb
    ports:
      - "8081:8081"

volumes:
  data:
  styles:
