version: '3.4'
services:
  # Dependant services
  ## Database (MongoDB) server
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: testtest
    volumes:
      - data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test -u admin -p testtest --authenticationDatabase admin --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s

  ## Database (MongoDB) GUI
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=dracula
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=testtest
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8081:8081"

  # EPP API
  api:
    build:
      context: .
      target: dev
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'apk add curl; curl http://api:3000/'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      REPO_TYPE: MongoDB
      REPO_CONNECTION: mongodb:27017
      REPO_USERNAME: admin
      REPO_PASSWORD: testtest
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/epp/src

  # expose API and client via proxy
  nginx:
    image: nginx:latest
    depends_on:
      api:
        condition: service_healthy
    ports:
    - 8080:80
    volumes:
    - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  data: {}
