services:
  # Dependant services
  image-server:
    build:
      context: image-server
    ports:
    - "8182:8182"
    volumes:
    - ./image-server/dev-cantaloupe.properties:/opt/cantaloupe/cantaloupe.properties
    - ./data:/opt/epp/data
    healthcheck:
      test: curl http://image-server:8182/
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: testtest
    volumes:
      - data:/home/couchdb/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=dracula
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=testtest
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8081:8081"

  # build styles
  sass-watch:
    build:
      context: .
      target: prod
    command: yarn sass:dev
    volumes:
    - ./src:/opt/epp/src
    - styles:/opt/epp/public/styles

  # main app
  app:
    build:
      context: .
      target: prod
    command: yarn start:dev
    environment:
      REPO_TYPE: MongoDB
      REPO_CONNECTION: mongodb:27017
      REPO_USERNAME: admin
      REPO_PASSWORD: testtest
      IIIF_SERVER: http://localhost:8182
    ports:
      - "8080:3000"
    volumes:
      - ./src:/opt/epp/src
      - styles:/opt/epp/public/styles
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'apk add curl; curl http://app:3000/'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
    depends_on:
      mongodb:
        condition: service_healthy
      image-server:
        condition: service_healthy

  # used to auto-import data
  import-data:
    image: alpine:latest
    command: sh -c "apk add curl; curl -X POST http://api:3000/import"
    depends_on:
      app:
        condition: service_healthy

volumes:
  data:
  styles:
