name: Pipeline

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'
          cache: yarn
      - name: yarn install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Unit Test
        run: yarn test
  build-and-push:
    needs: [test]
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --utc +%Y%m%d.%H%M)"
      -
        run: |
          timestamp=$(date --utc +%Y%m%d.%H%M)
          branch="${GITHUB_REF/refs\/heads\//}"
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          # docker build --no-cache -t $GITHUB_REPOSITORY:latest -t $GITHUB_REPOSITORY:${branch}-${GITHUB_SHA:0:8}-${timestamp} .
          # docker push --all-tags $GITHUB_REPOSITORY
          docker build --no-cache -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:${branch}-${GITHUB_SHA:0:8}-${timestamp} .
          docker push --all-tags $DOCKER_IMAGE_NAME

        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_IMAGE_NAME: "lunaaeterna/enhanced-preprint"
