name: Preview

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

jobs:
  build-preview-image:
    runs-on: ubuntu-20.04
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    steps:
      - uses: actions/checkout@v3
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "::set-output name=commit_sha::${GITHUB_SHA:0:8}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/elifesciences/enhanced-preprints:preview-${{ steps.commit_sha.outputs.commit_sha }}
